### ISSUE TITLE
Long tasks are out of the table in Firefox

### ISSUE THREAD

**Issue by dsasov** [tastejs/todomvc-app-css#14]
Bug reproduces only in Firefox browser
See attached: task name is out of the table

![screenshot from 2015-12-09 12 10 14](https://cloud.githubusercontent.com/assets/10956412/11682512/1a306890-9e6e-11e5-81a0-379f0b13b84c.png)

**Comment by anubhav7495** [comment]
This problem has already been fixed in the code as I remember. The version of todomvc-app-css used on the website is not up to date.

**Comment by anubhav7495** [comment]
Text overflow fix for Firefox #12 fixes this issue.

**Comment by samccone** [comment]
Yep! @anubhav7495 someone needs to mass update all of the examples... Any interest in helping here?

**Comment by anubhav7495** [comment]
I think instead of mass updating manually, we can define a grunt/gulp task to use github API to update the file.

**Comment by samccone** [comment]
wow yeah, if you wanted to do that... that would be even more amazing :tada:

**Comment by anubhav7495** [comment]
Or a task to just run npm update for all apps inside examples directory.

**Comment by anubhav7495** [comment]
@samccone i think we might have a problem updating our apps, as recently the todomvc-app-css file has been changed to use classes instead of ids and this functionality seems to break many apps when the css is updated to latest version.

**Comment by samccone** [comment]
Hey @anubhav7495 there are two versions of the app css

We have a 2x release and a 1x release  for exactly this reason :)

https://github.com/tastejs/todomvc-app-css/releases

**Comment by anubhav7495** [comment]
The 1x release does not have the correct code for this issue.
 Fixes Long Task Overflow #1549  is the solution i came up with.

**Comment by samccone** [comment]
@sindresorhus mind cutting a release of the 1.x channel with https://github.com/tastejs/todomvc-app-css/pull/12 ?

**Comment by anubhav7495** [comment]
https://github.com/tastejs/todomvc/pull/1549
The 1x release does not have the latest commit for fixing this issue

**Comment by sindresorhus** [comment]
@samccone I think the manual update was a better solution: https://github.com/tastejs/todomvc/pull/1549

**Comment by samccone** [comment]
work :+1:
