### ISSUE TITLE
Images doesn't work in IE/Edge

### ISSUE THREAD

**Issue by Alxandr** [tastejs/todomvc-app-css#19]
So, I was testing to see if my new and shiny library was working in IE after building a TodoMVC app in it (just to test stuff) and got the following:

![image](https://cloud.githubusercontent.com/assets/112334/13600438/16e4655e-e529-11e5-83b8-2049d95bc154.png)

I figured this was just something wrong with my webpack setup, but the same thing (more or less) happened when I visited http://todomvc.com/examples/react/#/ :

![image](https://cloud.githubusercontent.com/assets/112334/13600465/425c31e4-e529-11e5-9c58-fa7f9edf64a7.png)

This should probably be fixed IMHO.

**Comment by sindresorhus** [comment]
Should be fixed by https://github.com/tastejs/todomvc-app-css/commit/808217fab49a5e2da2d5e52aee417c62807cec28.
