### ISSUE TITLE
Checkbox SVG doesn't appear in Firefox

### ISSUE THREAD

**Issue by digitarald** [tastejs/todomvc-app-css#26]
Firefox 50 shows the checkbox input.

<img width="691" alt="screenshot 2017-05-08 13 23 21" src="https://cloud.githubusercontent.com/assets/8599/25823696/b4c5f324-33f1-11e7-9720-9758870596e7.PNG">

Firefox 54 shows no input or SVG:
<img width="691" alt="screenshot 2017-05-08 13 23 41" src="https://cloud.githubusercontent.com/assets/8599/25823695/b4c45c8a-33f1-11e7-84e9-1660fb6ef551.PNG">

**Comment by digitarald** [comment]
Step 1 for this fix is replacing the SVG data attributes with escaped characters. Firefox fails parsing `#` as invalid character.

**Comment by digitarald** [comment]
Looks like #8 fixed this but the latest version of this CSS has not been pulled into todomvc.com

**Comment by sindresorhus** [comment]
Open an issue on TodoMVC about that.

**Comment by digitarald** [comment]
Was already on file as well: https://github.com/tastejs/todomvc/issues/1780 thanks to patrickkettner
