### ISSUE TITLE
"Clear completed" vertical position

### ISSUE THREAD

**Issue by felixbuenemann** [tastejs/todomvc-app-css#3]
For me the "Clear completed" button is positioned wrongly, unless I include the following css:
```css
#clear-completed::after { top: 0 }
```
This happens to me when updating the styles on the todomvc example from the ember.js guide. I can't see any difference in the html compared to the official todomvc page, except maybe whitespace.

**Screenshot without Fix:**
![clear_completed_placement_problem](https://cloud.githubusercontent.com/assets/909587/6548907/eb855a6c-c607-11e4-9b6f-2ea2c57c0791.png)

**Screenshot with Fix:**
![clear_completed_placement_fix](https://cloud.githubusercontent.com/assets/909587/6548912/13d2a90c-c608-11e4-8f8b-4c9251774c06.png)

Tested on Chrome 43 / Mac OS X 10.10.3.

**Comment by samccone** [comment]
:+1: I ran into this also during a few of the upgrades, it is due to trailing whitespace, nasty tricky bit for sure

:goat:

**Comment by felixbuenemann** [comment]
@sindresorhus Thanks!
