### ISSUE TITLE
Switch to using classes

### ISSUE THREAD

**Issue by arthurvr** [tastejs/todomvc-app-css#4]
See original issue, https://github.com/tastejs/todomvc/issues/348. We want to switch all our ids over to classes. Than we should release v2 and start porting all of our apps over.

**Comment by sindresorhus** [comment]
Same with https://github.com/tastejs/todomvc-app-template

**Comment by sindresorhus** [comment]
We'll also need to update the https://github.com/tastejs/todomvc/blob/master/app-spec.md and the test suite.

// @ColinEberhardt

**Comment by arthurvr** [comment]
> We'll also need to update the https://github.com/tastejs/todomvc/blob/master/app-spec.md and the test suite.

Yup. What's the preferred way to handle the tests? I guess that if we switch them all over to classes all tests will fail. I don't think that's wanted as it might take a while for all apps to get updated.

**Comment by arthurvr** [comment]
Opened a PR for the template. Next up the tests and then I can start working on updating the apps.

**Comment by ColinEberhardt** [comment]
Regarding the tests, it looks like some changes were made a while back which allow them to switch between the use of classes or IDs to identify elements:

https://github.com/tastejs/todomvc/commit/90619f55c70ee70fb40caa8277cc1b4a1ccaeefa
